import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {

  contractsSidebar: [
    { type: "autogenerated", dirName: "Euclid Smart Contracts" },
  ],
  contractsSidebarSolidity: [
    { type: "autogenerated", dirName: "Euclid Solidity Contracts" },
  ],

  architectureSidebar: [
    "Architecture Overview/intro",
    "Architecture Overview/General Overview",
    {
      type: "category",
      label: "Concepts",
      items: [
        "Architecture Overview/Concepts/Liquidity Consensus Layer",
        "Architecture Overview/Concepts/Euclid Messaging Protocol",
        "Architecture Overview/Concepts/Global Settlement Accounts",
        "Architecture Overview/Concepts/Smart Routing",
        "Architecture Overview/Concepts/Vouchers",
        "Architecture Overview/Concepts/Meta Transactions",
        "Architecture Overview/Automated-Market-Makers",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      items: [
        {
          type: "category",
          label: "Integrated Chains Layer",
          items: [
            "Architecture Overview/Architecture/Integrated Chains Layer/factory",
            "Architecture Overview/Architecture/Integrated Chains Layer/escrows",
          ],
        },
        {
          type: "category",
          label: "Virtual Settlement Layer",
          items: [
            "Architecture Overview/Architecture/Virtual Settlement Layer/virtual-settlement-layer",
            "Architecture Overview/Architecture/Virtual Settlement Layer/virtual-pools",
            "Architecture Overview/Architecture/Virtual Settlement Layer/virtual-balances",
          
            
          ],
        },
        "Architecture Overview/Architecture/router",
      ],
    },
  ],
  
  apiSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "API/Getting Started/Initial Setup",
        "API/Getting Started/First Call",
        "API/Getting Started/API Prerequisites and Chain Configuration",
        "API/Getting Started/Perform A Swap",
        "API/Getting Started/Broadcast Trade Onchain",
      ],
    },
    {
      type: "category",
      label: "Trading",
      items: [
        {
          type: "category",
          label: "Endpoints",
          items: [
            "API/Trading/Endpoints/Fetch Assets",
            "API/Trading/Endpoints/Fetch Chains",
            "API/Trading/Endpoints/Fetch Liquidity",
            "API/Trading/Endpoints/Fetch Voucher",
            "API/Trading/Endpoints/Track Transaction",
            "API/Withdraw Voucher",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Liquidity Provisioning",
      items: [
        "API/Liquidity Provisioning/Fees and Rewards",
        "API/Liquidity Provisioning/Euclid Pools",
        {
          type: "category",
          label: "Different Liquidity States",
          items: [
            "API/Liquidity Provisioning/Different Liquidity States/Stable Pool",
            "API/Liquidity Provisioning/Different Liquidity States/Constant Product Pool",
          ],
        },
        {
          type: "category",
          label: "Endpoints",
          items: [
            "API/Liquidity Provisioning/Endpoints/Fetch Liquidity",
            "API/Liquidity Provisioning/Endpoints/Create Pool",
            "API/Liquidity Provisioning/Endpoints/Add Liquidity",
            "API/Liquidity Provisioning/Endpoints/Remove Liquidity",
            "API/Liquidity Provisioning/Endpoints/Provider Position",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Pricing",
      items: [
        "API/Pricing/Route Calculation",
        "API/Pricing/Slippage",
        "API/Pricing/Risks and Impermanent Loss",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      items: [
        {
          type: "category",
          label: "Aggregators",
          items: [
            "API/Integrations/Aggregators/Intro",
            "API/Integrations/Aggregators/get-routes",
            "API/Integrations/Aggregators/create-swap-payload",
            "API/Integrations/Aggregators/broadcast",
            "API/Integrations/Aggregators/track-execution",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "API Reference",
      items: [
        "API/API Reference/Intro",
        "API/API Reference/common types",
        {
          type: "category",
          label: "GQL",
          items: [
            {
              type: "category",
              label: "Router",
              items: [
                "API/API Reference/GQL/Router/All Chains",
                "API/API Reference/GQL/Router/All Tokens",
                "API/API Reference/GQL/Router/All VLPs",
                "API/API Reference/GQL/Router/All Escrows",
                "API/API Reference/GQL/Router/Chain",
                "API/API Reference/GQL/Router/Escrows",
                "API/API Reference/GQL/Router/Simulate Escrow Release",
                "API/API Reference/GQL/Router/Simulate Swap",
                "API/API Reference/GQL/Router/State",
                "API/API Reference/GQL/Router/VLP",
                "API/API Reference/GQL/Router/Token Pair From VLP",
                "API/API Reference/GQL/Router/Token Denoms"

              ],
            },
            {
              type: "category",
              label: "Factory",
              items: [
                "API/API Reference/GQL/Factory/All Pools",
                "API/API Reference/GQL/Factory/All tokens",
                "API/API Reference/GQL/Factory/Escrow",
                "API/API Reference/GQL/Factory/Get Token Address",
                "API/API Reference/GQL/Factory/State",
                "API/API Reference/GQL/Factory/VLP",
                "API/API Reference/GQL/Factory/Allowed Denoms",
                "API/API Reference/GQL/Factory/Partner Fees Collected",
              ],
            },
            {
              type: "category",
              label: "Chain",
              items: [
                "API/API Reference/GQL/Chain/All Chains",
                "API/API Reference/GQL/Chain/Chain Config",
                "API/API Reference/GQL/Chain/Contracts",
                "API/API Reference/GQL/Chain/Router Config",
                "API/API Reference/GQL/Chain/Keplr Config",
                "API/API Reference/GQL/Chain/EVM Chain Config",
                "API/API Reference/GQL/Chain/All EVM Chains",

              ],
            },
            {
              type: "category",
              label: "VLP",
              items: [
                "API/API Reference/GQL/VLP/All Pools",
                "API/API Reference/GQL/VLP/Fee",
                "API/API Reference/GQL/VLP/Liquidity",
                "API/API Reference/GQL/VLP/Pool",
                "API/API Reference/GQL/VLP/State",
                "API/API Reference/GQL/VLP/Total Fees Collected",
                "API/API Reference/GQL/VLP/Total Fees Denom",
              ],
            },
            {
              type: "category",
              label: "Pool",
              items: [
                "API/API Reference/GQL/Pool/My Pools",
                "API/API Reference/GQL/Pool/Volume",
                "API/API Reference/GQL/Pool/Fees Collected",
                "API/API Reference/GQL/Pool/Token Pair With Liquidity",
              ],
            },
            {
              type: "category",
              label: "CW",
              items: [
                "API/API Reference/GQL/CW/Balance",
                "API/API Reference/GQL/CW/Token Info",
              ],
            },
            {
              type: "category",
              label: "Token",
              items: [
                "API/API Reference/GQL/Token/Token Metadata by Id",
                "API/API Reference/GQL/Token/Token Metadata",
                "API/API Reference/GQL/Token/Token Liquidities",
                "API/API Reference/GQL/Token/Token Liquidity",
                "API/API Reference/GQL/Token/Token Denoms",
                "API/API Reference/GQL/Token/Dex Metadata",
                "API/API Reference/GQL/Token/All Dexes",
                "API/API Reference/GQL/Token/Get Faucets",
              ],
            },
            {
              type: "category",
              label: "Virtual Balance",
              items: [
                "API/API Reference/GQL/Virtual Balance/Balance",
                "API/API Reference/GQL/Virtual Balance/State",
                "API/API Reference/GQL/Virtual Balance/User Balance",
                "API/API Reference/GQL/Virtual Balance/Unified User Balance",
              ],
            },
            "API/API Reference/GQL/GQL Calls",
          ],
        },
        {
          type: "category",
          label: "REST",
          items: [
            {
              type: "category",
              label: "Routes",
              items: [
                "API/API Reference/REST/Routes/Get Routes",
              ],
            },
            {
              type: "category",
              label: "Transactions",
              items: [
                "API/API Reference/REST/Transactions/Swap",
                "API/API Reference/REST/Transactions/Simulate Swap",
                {
                  type: "category",
                  label: "Liquidity",
                  items: [
                    "API/API Reference/REST/Transactions/Liquidity/Add Liquidity",
                    "API/API Reference/REST/Transactions/Liquidity/Create Pool",
                    "API/API Reference/REST/Transactions/Liquidity/Remove Liquidity",
                  ],
                },
                {
                  type: "category",
                  label: "Tracking",
                  items: [
                    "API/API Reference/REST/Transactions/Tracking/Track Swap Transaction",
                    "API/API Reference/REST/Transactions/Tracking/Track Transactions",
                  ],
                },
                {
                  type: "category",
                  label: "Vouchers",
                  items: [
                    "API/API Reference/REST/Transactions/Vouchers/Deposit",
                    "API/API Reference/REST/Transactions/Vouchers/Transfer Voucher",
                    "API/API Reference/REST/Transactions/Vouchers/Withdraw Virtual Balance",
                  ],
                },
                {
                  type: "category",
                  label: "Meta Transactions",
                  items: [
                    "API/API Reference/REST/Transactions/Meta Transactions/Intro",
                    "API/API Reference/REST/Transactions/Meta Transactions/Swap",
                    "API/API Reference/REST/Transactions/Meta Transactions/Transfer",
                    "API/API Reference/REST/Transactions/Meta Transactions/Withdraw",
                    "API/API Reference/REST/Transactions/Meta Transactions/Sign",
                    "API/API Reference/REST/Transactions/Meta Transactions/Broadcast",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
