import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "Architecture Overview" },
  ],
  contractsSidebar: [
    { type: "autogenerated", dirName: "Euclid Smart Contracts" },
  ],
  contractsSidebarSolidity: [
    { type: "autogenerated", dirName: "Euclid Solidity Contracts" },
  ],
  apiSidebar: [
    "API/Intro",
    {
      type: "category",
      label: "GQL",
      items: [
        {
          type: "category",
          label: "Router",
          items: [
            "API/GQL/Router/All Chains",
            "API/GQL/Router/All Tokens",
            "API/GQL/Router/All VLPs",
            "API/GQL/Router/All Escrows",
            "API/GQL/Router/Chain",
            "API/GQL/Router/Escrows",
            "API/GQL/Router/Simulate Escrow Release",
            "API/GQL/Router/Simulate Swap",
            "API/GQL/Router/State",
            "API/GQL/Router/VLP",
            "API/GQL/Router/Token Pair From VLP",
            "API/GQL/Router/Token Denoms"

          ],
        },
        {
          type: "category",
          label: "Factory",
          items: [
            "API/GQL/Factory/All Pools",
            "API/GQL/Factory/All tokens",
            "API/GQL/Factory/Escrow",
            "API/GQL/Factory/Get Token Address",
            "API/GQL/Factory/State",
            "API/GQL/Factory/VLP",
            "API/GQL/Factory/Allowed Denoms",
            "API/GQL/Factory/Partner Fees Collected",
          ],
        },
        {
          type: "category",
          label: "Chain",
          items: [
            "API/GQL/Chain/All Chains",
            "API/GQL/Chain/Chain Config",
            "API/GQL/Chain/Contracts",
            "API/GQL/Chain/Router Config",
            "API/GQL/Chain/Keplr Config",
            "API/GQL/Chain/EVM Chain Config",

          ],
        },
        {
          type: "category",
          label: "VLP",
          items: [
            "API/GQL/VLP/All Pools",
            "API/GQL/VLP/Fee",
            "API/GQL/VLP/Liquidity",
            "API/GQL/VLP/Pool",
            "API/GQL/VLP/State",
            "API/GQL/VLP/Total Fees Collected",
            "API/GQL/VLP/Total Fees Denom",
          ],
        },
        {
          type: "category",
          label: "Pool",
          items: [
            "API/GQL/Pool/My Pools",
            "API/GQL/Pool/Volume",
            "API/GQL/Pool/Fees Collected",
            "API/GQL/Pool/Token Pair With Liquidity",
          ],
        },
        {
          type: "category",
          label: "CW",
          items: ["API/GQL/CW/Balance", "API/GQL/CW/Token Info"],
        },
        {
          type: "category",
          label: "Token",
          items: [
            "API/GQL/Token/Token Metadata by Id",
            "API/GQL/Token/Token Metadata",
            "API/GQL/Token/Token Liquidities",
            "API/GQL/Token/Token Liquidity",
            "API/GQL/Token/Token Denoms",
            "API/GQL/Token/Dex Metadata",
            "API/GQL/Token/Get Faucets",
          ],
        },
        {
          type: "category",
          label: "Virtual Balance",
          items: [
            "API/GQL/Virtual Balance/Balance",
            "API/GQL/Virtual Balance/State",
            "API/GQL/Virtual Balance/User Balance",
          ],
        },
        "API/GQL/GQL Calls",
      ],
    },
    {
      type: "category",
      label: "REST",
      items: [
        {
          type: "category",
          label: "Routes",
          items: [
            "API/REST/Routes/Get Routes",
          ],
        },
        {
          type: "category",
          label: "Transactions",
          items: [
            "API/REST/Transactions/Swap",
            "API/REST/Transactions/Add Liquidity",
            "API/REST/Transactions/Remove Liquidity",
            "API/REST/Transactions/Track Transactions",
            "API/REST/Transactions/Withdraw Virtual Balance",
            "API/REST/Transactions/Track Swap Transaction",
            "API/REST/Transactions/Create Pool",
            "API/REST/Transactions/Deposit",
          ],
        },
        
      ],
    },
    {
      type: "category",
      label: "Developer Guides ",
      items: [
        "API/Developer Guides/Introduction",
        "API/Developer Guides/Swap",
        "API/Developer Guides/Add Liquidity",
        "API/Developer Guides/Remove Liquidity",
        "API/Developer Guides/Withdraw Voucher",
      ],
    },
  ],
};

export default sidebars;
