import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "Architecture Overview" },
  ],
  contractsSidebar: [
    { type: "autogenerated", dirName: "Euclid Smart Contracts" },
  ],
  contractsSidebarSolidity: [
    { type: "autogenerated", dirName: "Euclid Solidity Contracts" },
  ],
  apiSidebar: [
    "API/Intro",
    {
      type: "category",
      label: "Developer Guides",
      items: [
        "API/Developer Guides/Add Liquidity",
        "API/Developer Guides/Introduction",
        "API/Developer Guides/Remove Liquidity",
        "API/Developer Guides/Swap",
        "API/Developer Guides/Withdraw Voucher",
      ],
    },
    {
      type: "category",
      label: "GQL",
      items: [
        "API/GQL/GQL Calls",
        {
          type: "category",
          label: "Router",
          items: [
            "API/GQL/Router/All Chains",
            "API/GQL/Router/All Tokens",
            "API/GQL/Router/All VLPs",
            "API/GQL/Router/Chain",
            "API/GQL/Router/Escrows",
            "API/GQL/Router/Simulate Escrow Release",
            "API/GQL/Router/Simulate Swap",
            "API/GQL/Router/State",
            "API/GQL/Router/VLP",
          ],
        },
        {
          type: "category",
          label: "Factory",
          items: [
            "API/GQL/Factory/All Pools",
            "API/GQL/Factory/All tokens",
            "API/GQL/Factory/Escrow",
            "API/GQL/Factory/Get Token Address",
            "API/GQL/Factory/State",
            "API/GQL/Factory/VLP",
          ],
        },
        {
          type: "category",
          label: "Chain",
          items: [
            "API/GQL/Chain/All Chain UIDs",
            "API/GQL/Chain/Chain Config",
            "API/GQL/Chain/Chain UID",
            "API/GQL/Chain/Chiain Id",
            "API/GQL/Chain/Contracts",
            "API/GQL/Chain/Router",
          ],
        },
        {
          type: "category",
          label: "VLP",
          items: [
            "API/GQL/VLP/All Pools",
            "API/GQL/VLP/Fee",
            "API/GQL/VLP/Liquidity",
            "API/GQL/VLP/Pool",
            "API/GQL/VLP/State",
          ],
        },
        {
          type: "category",
          label: "Pool",
          items: [
            "API/GQL/Pool/My Pools",
            "API/GQL/Pool/Token Liquidities",
            "API/GQL/Pool/Token Liquidity",
            "API/GQL/Pool/Volume",
          ],
        },
        {
          type: "category",
          label: "CW",
          items: ["API/GQL/CW/Balance", "API/GQL/CW/Token Info"],
        },
        {
          type: "category",
          label: "Token",
          items: [
            "API/GQL/Token/Token Metadata by Id",
            "API/GQL/Token/Token Metadata",
          ],
        },
        {
          type: "category",
          label: "Virtual Balance",
          items: [
            "API/GQL/Virtual Balance/Balance",
            "API/GQL/Virtual Balance/State",
            "API/GQL/Virtual Balance/User Balance",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "REST",
      items: [
        {
          type: "category",
          label: "Chains",
          items: ["API/REST/Chains/Get Chains"],
        },
        {
          type: "category",
          label: "Contracts",
          items: ["API/REST/Contracts/Get Contracts"],
        },
        {
          type: "category",
          label: "Metadata",
          items: [
            "API/REST/Metadata/Get Token Details",
            "API/REST/Metadata/Token Price",
          ],
        },
        {
          type: "category",
          label: "Routes",
          items: ["API/REST/Routes/Get Routes"],
        },
        {
          type: "category",
          label: "Transactions",
          items: [
            "API/REST/Transactions/Add Liquidity",
            "API/REST/Transactions/Remove Liquidity",
            "API/REST/Transactions/Simulate Swap",
            "API/REST/Transactions/Swap",
            "API/REST/Transactions/Track Transactions",
            "API/REST/Transactions/Withdraw Virtual Balance",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
